### ISSUE TITLE
import problems

### ISSUE THREAD

**Issue by levaifelasticad** [ajainarayanan/react-pan-zoom#5]
Hi
I added your component to my project 
yarn add react-pan-zoom

but I have this error when I try to import it 

import ReactPanZoom from 'react-pan-zoom';

Unable to resolve path to module 'react-pan-zoom'.eslint(import/no-unresolved)
Missing file extension for "react-pan-zoom"eslint(import/extensions)

What i do wrong ?

**Comment by nsallis** [comment]
I'm seeing this too. Looks like the 0.0.2 release broke the import for some reason.

**Comment by nsallis** [comment]
`yarn add react-pan-zoom` will not add this package, it adds this: https://www.npmjs.com/package/react-pan-zoom, which is by a different author. If you add `@ajainarayanan/react-pan-zoom`, which is this package, then you will need to set the version in your package.json to 0.0.1, until @ajainarayanan rebuilds the npm package since v0.0.2 currently has no dist directory. 

package.json:
"@ajainarayanan/react-pan-zoom": "0.0.1", ...

component/react file:
import ReactPanZoom from "@ajainarayanan/react-pan-zoom";

I expect the eslint issue is because you are trying to load the other package instead of this one. If it continues after switching to this package, then please post your eslint file and package.json.

**Comment by ajainarayanan** [comment]
@levaifelasticad @nsallis I have published 0.0.3 with proper dist folder. Could you give it a try and let me know if that works?

**Comment by nsallis** [comment]
Works great now, thanks! I think we can close this.
