### ISSUE TITLE
Can't reset the  component's position

### ISSUE THREAD

**Issue by malvf** [ajainarayanan/react-pan-zoom#6]
Hello, I am trying to reposition my component by using the onPan callback function like in your example https://codesandbox.io/s/q8wl1joow9
It seems that by using ReactPanZoom instead of StyledReactPanZoom , the component's position cannot be changed.
The component's state of DX and DY is updated , but the transform-matrix's values (4,5) seems not to update in the DOM.
The zoom and pan features are working!

Regards, M.F

**Comment by ajainarayanan** [comment]
@malvf I see. Somethings for clarification 
- What is it that you wanted to do in your `onPan` function? The objective of the `onPan` function is to propagate the dx and dy value changes to the parent component using `ReactPanZoom`.
- Right now there is only `onPan` callback (and not onZoom callback) because the dx and dy values are changed within the `ReactPanZoom` and `onPan` callback is the only way to propagate those values to the parent component.
- You have a callback function for `onPan` prop. But you seem to be setting the dx and dy that is passed on to the function to your state which is eventually passed onto `ReactPanZoom`.
This is not the intended behavior. The `pandx` and `pandy` values are accepted only during initialization. Once initialized the component takes care of managing the `dx` and `dy` for you.

Can you provide more details on what is the objective of `onPan` callback and why do you need to control the dx and dy from outside the component when it is already managed within it?

**Comment by malvf** [comment]
@ajainarayanan Hello. So, my main goal is to have a function that resets the initial position and the zoom of the component that is nested in <ReactPanZoom/>. So far, I managed to reset the initial zoom by setting the state as 1. I am trying to set the dx and the dy to 0 in the same function, but it is not working. I checked the transform-matrix property after the function was called and I found that the zoom's value is updated, although the dx and dy are not. 

Unfortunately, I can't provide the full code. The function looks like this

``resetScale() {
		this.setState({
			zoom: 1,
                       dx:0,
                       dy:0
			organogramData: cloneDeep(this.resetData)
		});
	}

My onPen callback it's exactly like yours in the codePen.

**Comment by ajainarayanan** [comment]
@malvf Hhmm this is not possible today. The cwrp life cycle function needs to be updated. PRs welcome!

**Comment by Bobface** [comment]
I just wanted to do the same thing as OP. Would be a great addition indeed!

**Comment by JoshuaSoileau** [comment]
+1

**Comment by ajainarayanan** [comment]
Sorry for the super late response. 
@malvf https://github.com/ajainarayanan/react-pan-zoom/pull/7 Have added a fix as PR. Can you review and see if that works for you?

If all looks good will merge and will release a version.

**Comment by foteros** [comment]
+1

**Comment by ajainarayanan** [comment]
For anyone who is +1'ing this issue can you help review the pull request?

**Comment by mattbilbow** [comment]
Thanks for the PR. Looks good to me.

+1

**Comment by awtyklo** [comment]
+1

**Comment by mohamed2a** [comment]
+100

**Comment by ajainarayanan** [comment]
Changes available as part of 0.0.4 version.
